import os
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import os
import shutil
import argparse
import utils

systemd_unit_file = """
[Unit]
Description=A lightweight personal stroage solution
After=network.service

[Service]
ExecStart=/usr/local/bin/tinycloud -c /etc/tinycloud

[Install]
WantedBy=multi-user.target
"""

src_dir = os.path.join(os.path.dirname(__file__), "conf/")

parser = argparse.ArgumentParser()
parser.add_argument("config", help="path to install")
parser.add_argument("--systemd", help="install systemd unit file", action="store_true")
args = parser.parse_args()
if args.config:
    dst_dir = args.config
else:
    dst_dir = "conf/"

# if not os.path.exists(dir):
#   os.mkdir(dir)
shutil.copytree(src_dir, dst_dir, dirs_exist_ok=True)

secret = """
#Generated by system,do not edit
secret: {}
""".format(
    utils.random_string(100)
)

with open(os.path.join(dst_dir, "config.yaml"), "a") as config_file:
    config_file.write(secret)

if args.systemd:
    with open("/lib/systemd/system/tinycloud.service", "w") as unit_file:
        unit_file.write(systemd_unit_file)
